services:
  - type: web
    name: tropicom-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tropicom_site.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tropicom_site.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
