# Generated by Django 5.2.1 on 2025-07-24 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Abonné à la newsletter', 'verbose_name_plural': 'Abonnés à la newsletter'},
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='date_inscription',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='date_subscribed',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 24, 8, 41, 59, 567929, tzinfo=datetime.timezone.utc), verbose_name="Date d'abonnement"),
            preserve_default=False,
        ),
    ]
