# Generated by Django 5.2.1 on 2025-07-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_joboffer_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
