# Generated by Django 5.2.1 on 2025-06-22 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorieservice',
            options={'verbose_name': 'Catégorie de service', 'verbose_name_plural': 'Catégories de services'},
        ),
        migrations.AlterModelOptions(
            name='informationssite',
            options={'verbose_name': 'Informations du site', 'verbose_name_plural': 'Informations du site'},
        ),
        migrations.AlterModelOptions(
            name='messagecontact',
            options={'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='categorieservice',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom de la catégorie'),
        ),
        migrations.AlterField(
            model_name='informationssite',
            name='a_propos',
            field=models.TextField(verbose_name='À propos'),
        ),
        migrations.AlterField(
            model_name='informationssite',
            name='adresse',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='informationssite',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='informationssite',
            name='nom_entreprise',
            field=models.CharField(max_length=100, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='informationssite',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='date_envoye',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='sujet',
            field=models.CharField(max_length=150, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='service',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.categorieservice', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='titre',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
    ]
